//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by testGSLib_dyn.rc
//
#define IDS_HELLO                       1
#define IDD_functions                   101
#define IDC_functions                   1000
#define IDC_RUN                         1001
#define IDC_tests                       1003
#define IDC_funcinit                    1005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
