//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GSLib_dyn.rc
//
#define IDP_SOCKETS_INIT_FAILED         101
#define IDD_InputCoordinator            1000
#define IDD_InputPartModification       1001
#define IDC_fileName                    1002
#define IDC_timetable                   1004
#define IDC_ADD                         1005
#define IDC_portname                    1007
#define IDC_dim                         1008
#define IDC_check                       1009
#define IDC_time                        1010
#define IDC_init                        1012
#define IDC_internal                    1013
#define IDC_external                    1014
#define IDC_print                       1015
#define IDC_Delete                      1016
#define IDC_Load                        1017
#define IDC_Save                        1018
#define IDC_InputData                   1019
#define IDC_dmanual                     1020
#define IDC_automatic                   1021
#define IDC_rep                         1022
#define IDC_prev                        1023
#define IDC_next                        1024
#define IDC_modify                      1025
#define IDC_gDim                        1026
#define IDC_error                       1027
#define IDC_clkprec                     1028
#define IDC_clkadvance                  1029
#define IDC_reset                       1030
#define IDC_relinkup                    1031
#define IDC_relinkdown                  1033
#define IDC_wantport                    1034
#define IDC_wantproc                    1035
#define IDC_wantnet                     1036
#define IDC_standalone                  1037
#define IDC_fromproc                    1038
#define IDC_fromnet                     1039
#define IDC_element                     1040
#define IDC_level_reset                 1042
#define IDC_level_up                    1043
#define IDC_level_down                  1044
#define IDC_level                       1045
#define IDC_del                         1046
#define IDC_levels                      1047
#define IDC_brother                     1049
#define IDC_copy                        1050
#define IDC_new                         1051
#define IDC_addelem                     1053
#define IDC_copyport                    1054
#define IDC_copyproc                    1055
#define IDC_copynet                     1056
#define IDC_copy_reset                  1062
#define IDC_copy_up                     1063
#define IDC_copy_down                   1064
#define IDC_copy_level                  1065
#define IDC_copy_element                1066
#define IDC_copy_from                   1067
#define IDC_copy_levels                 1068
#define IDC_copy_standalone             1069
#define IDC_copy_fromproc               1070
#define IDC_copy_fromnet                1071
#define IDC_same                        1073
#define IDC_newwire                     1074
#define IDC_toproc                      1075
#define IDC_tonet                       1076
#define IDC_toparent                    1077
#define IDC_fromtoport                  1078
#define IDC_toport                      1079
#define IDC_in                          1080
#define IDC_out                         1081
#define IDC_wireshist                   1082
#define IDC_addwire                     1083
#define IDC_errors_messages             1084
#define IDC_topart                      1085
#define IDC_from                        1086
#define IDC_up_levels                   1087
#define IDC_new_old                     1088
#define IDC_oldelem                     1089
#define IDC_pas_act                     1090
#define IDC_all                         1091
#define IDC_input                       1094
#define IDC_output                      1095

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1002
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1096
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
